#pragma once

#include <string>
#include <memory>
#include <array>
// ROOT dependencies
#include <TH1.h>
#include <TFile.h>  
#include <TTree.h>
#include <TDirectory.h>

/**
  @brief Class to parse .root files containing the angular distribution of Cherenkov photons.

  This class derives from TFile and specializes at reading files with the angular distribution of Cherenkov photons generated by
  the read-cerenk COAST interface to CORSIKA. The constructor takes the path to a valid file.

  It has methods that are specialized to parse the file sequentially within for loops.

  TODO: implement checks and error handling.

  @author Luan Arbeletche
  @date July 2020
 */
class CerenkovHistogramFile : public TFile
{
private:

  std::unique_ptr<TTree> eventTreePointer; /**< Pointer to the TTree object with information from CORSIKA EVENT blocks*/
  std::unique_ptr<TTree> runTreePointer; /**< Pointer to the TTree object with information from CORSIKA RUN blocks*/

  std::array<float, 273> eventHeaderArray; /**< Array holding information from EVENT HEADER blocks */
  std::array<float, 273> eventEndArray; /**< Array holding information from EVENT END blocks */
  std::array<float, 273> runHeaderArray; /**< Array holding information from RUN HEADER blocks */
  std::array<float, 273> runEndArray; /**< Array holding information from RUN END blocks */

  int numberOfShowers; /**< Number of shower in the file */
  int nextShower; /**< Index pointing to the next shower */
  
  std::unique_ptr<TDirectory> eventDirectoryPointer; /**< A pointer to the event directory being read */
  std::unique_ptr<TH1> rhoHistogram; /**< A pointer to the atmospheric density profile for the current event */
  std::unique_ptr<TH1> ageHistogram; /**< A pointer to the shower age profile for the current event */
  std::unique_ptr<TH1> refHistogram; /**< A pointer to the refractive index profile for the current event */
  int currentRunNumber; /**< Index of the run number of the current event */
  int currentEventNumber; /**< Index of the event number of the current event */
  
  int nextHistogram; /**< Index pointing to the next histogram within the current event */
  int numberOfHistograms; /**< Number of histograms available in this event */
  double currentAge; /**< Shower age associated with the current histogram */
  double currentDeltaAge; /**< Width of the age interval associated with the current histogram */
  double currentRefractiveIndex; /**< Refractive index at the emission point for the current histogram */
  double currentDensity; /**< Atmospheric density at the emission point for the current histogram */
  int currentAtmosphericBin; /**< Index of the atmospheric depth bin associated with the current histogram */
  std::unique_ptr<TH1> currentThetaHistogram; /**< Pointer to the current histogram */
  
  double showerZenith; /**< Zenith angle of the current shower */
  double showerEnergy; /**< Primary energy of the current shower */
  double showerAzimuth; /**< Azimuthal angle of the current shower */
  
  static const double vAtmH[5]; /**< Threshold altitudes for US Standard Atmosphere according to CORSIKA manual */
  static const double vAtmA[5]; /**< Parameters A describing the US Standard Atmosphere according to CORSIKA */
  static const double vAtmB[5]; /**< Parameters B describing the US Standard Atmosphere according to CORSIKA */
  static const double vAtmC[5]; /**< Parameters C describing the US Standard Atmosphere according to CORSIKA */
  static const double vMeanH[20]; /**< Array of altitudes associated to the bins in atmospheric depth */

public:
  /**
    Main constructor.
    Opens a file with histograms and reads data trees with run/event info.
    @param histogramFileName - path to the .root file to be opened
   */
  CerenkovHistogramFile(std::string histogramFileName);

  /**
    Reads next shower.
    @return true if a next shower exists, otherwise return false.
   */
  bool NextShower();

  /**
    Reads next next histogram in current shower.
    @return true if next histogram exists, otherwise return false.
   */
  bool NextHistogram();

  /**
    Reads shower with given ID.
    @param showerID - ID of the shower to be read.
    @return true if shower with given ID exists, otherwise return false.
   */
  bool ReadShower(int showerId);

  /**
    Reads histogram with given ID in the current shower.
    @param histogramID - ID of the histogram to be read.
    @return true if histogram with given ID exists, otherwise return false.
   */
  bool ReadHistogram(int histogramId);
  
  /**
    Get current run number.
    @return Current run number
   */
  int GetRunNumber() const
  {
    return this->currentRunNumber;
  }

  /**
    Get current event number.
    @return Current event number
   */
  int GetEvtNumber() const
  {
    return this->currentEventNumber;
  }

  /**
    Get index of the atmospheric bin associated with current histogram.
    @return Current atmospheric bin
   */
  int GetAtmosphericBin() const
  {
    return this->currentAtmosphericBin;
  }

  /**
    Get shower age associated with the current histogram
    @return Current shower age
   */
  double GetAge() const
  {
    return this->currentAge;
  }

  /**
    Get width of the shower age interval associated with the current histogram.
    @return Width of current shower age interval
   */
  double GetDeltaAge() const
  {
    return this->currentDeltaAge;
  }

  /**
    Get refractive index associated with the current histogram.
    @return Current refractive index
   */
  double GetRefractiveIndex() const
  {
    return this->currentRefractiveIndex;
  }

  /**
    Get atmospheric density associated with the current histogram.
    @return Current atmospheric density
   */
  double GetDensity() const
  {
    return this->currentDensity;
  }

  /**
    Get average altitude associated with the current histogram.
    @return Average altitude
   */
  double GetMeanHeight() const
  {
    return CerenkovHistogramFile::vMeanH[this->currentAtmosphericBin-1];
  }

  /**
    Get energy of the current shower.
    @return Primary energy
   */
  double GetShowerEnergy() const
  {
    return this->showerEnergy;
  }

  /**
    Get zenith angle of the current shower
    @return Primary zenith angle
   */
  double GetShowerZenith() const
  {
    return this->showerZenith;
  }

  /**
    Get azimuth of the current shower
    @return Primary azimuth angle
   */
  double GetShowerAzimuth() const
  {
    return this->showerAzimuth;
  }

  /**
    Get a pointer to the current histogram. Beware!
   */
  TH1 * GetThetaHistogramPointer() const
  {
    return this->currentThetaHistogram.get();
  }
  
  /**
    Compute altitude given atmospheric depth according to US standard atmospheric model.
    @param depth - Atmospheric depth
    @return Altitude corresponding to given depth
   */
  static double AtmHeight(double depth);

  /**
    Compute atmospheric depth given altitude according to US standard atmospheric model.
    @param heigth - Altitude
    @return Atmospheric depth corresponding to given altitude
   */
  static double AtmDepth(double height);

  /**
    Compute refractiveIndex - 1.0 for given altitude.
    @param height Altitude
    @return Refractive index - 1.0 for given altitude.
   */
  static double AtmDelta(double height);

  /**
    Compute atmospheric density given altitude according to US standard atmospheric model.
    @param heigth - Altitude
    @return Atmospheric density corresponding to given altitude
   */
  static double AtmRho(double height);
};
